# Generated by Django 4.2.4 on 2023-08-09 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 8, 9, 14, 11, 54, 106232, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
