# Generated by Django 4.2.4 on 2023-08-09 14:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
